/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInputTag: typeof import('@arco-design/web-vue')['InputTag']
    ARate: typeof import('@arco-design/web-vue')['Rate']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
