// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    GoodsItem: typeof import('./src/components/Goods/GoodsItem.vue')['default']
    GoodsItem3: typeof import('./src/components/Goods/GoodsItem3.vue')['default']
    GoodsItemForMenu: typeof import('./src/components/Goods/GoodsItemForMenu.vue')['default']
    GoodsItemForOrder: typeof import('./src/components/Goods/GoodsItemForOrder.vue')['default']
    GoodsitemOrder2: typeof import('./src/components/Goods/GoodsitemOrder2.vue')['default']
    GoodsitemOrderinfo: typeof import('./src/components/Goods/GoodsitemOrderinfo.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    README: typeof import('./src/components/Dialog/README.md')['default']
    VanArea: typeof import('vant/es')['Area']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPasswordInput: typeof import('vant/es')['PasswordInput']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

export { }
