export const ledgerPartyThead = [
    { align: 'center', tooltip: true, prop: 'entityUserId', label: '柜主id', minWidth: 150, fixed: 'left' },
    { align: 'center', tooltip: true, prop: 'entityUserName', label: '柜主姓名', maxWidth: 90, fixed: 'left' },
    { align: 'center', tooltip: true, prop: 'entityUserMobile', label: '柜主手机号', maxWidth: 120 },
    { align: 'center', tooltip: true, prop: 'subLedgerId', label: '分账方Id', slot: true },
    { align: 'center', tooltip: true, prop: 'mobile', label: '分账方手机号' },
    { align: 'center', tooltip: true, prop: 'typeDesc', label: '分账接收方类型' },
    { align: 'center', tooltip: true, prop: 'subLedgerTypeDesc', label: '分账方角色', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'name', label: '分账方/企业名称' },
    { align: 'center', tooltip: true, prop: 'channelDesc', label: '渠道' },
    { align: 'center', tooltip: true, prop: 'accountId', label: '分账方openid/商户号', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'nickname', label: '分账方昵称/商户号', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'statusDesc', label: '状态' },
    { align: 'center', tooltip: true, prop: 'cooperationStatusDesc', label: '合作状态' },
    { align: 'center', tooltip: true, prop: 'unbindingTime', label: '解绑时间', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'createTime', label: '配置时间', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'enableStatusDesc', label: '是否启用', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'enableTime', label: '启用时间', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'showStatusDesc', label: '是否显示', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'operate', label: '操作', minWidth: 100, slot: true }
]
export const gridDataThead = [
    { align: 'center', tooltip: true, prop: 'name', label: '分账方名称' },
    { align: 'center', tooltip: true, prop: 'mobile', label: '分账方手机号' },
    { align: 'center', tooltip: true, prop: 'type', label: '类型', slot: true },
    { align: 'center', tooltip: true, prop: 'accountNo', label: '分账方openid/商户号', width: 170 },
    { align: 'center', tooltip: true, prop: 'collectionMerchantNo', label: '分账方平台商户号' },
    { align: 'center', tooltip: true, prop: 'amount', label: '分账金额(元)', slot: true },
    { align: 'center', tooltip: true, prop: 'rate', label: '分账方分账比例', slot: true },
    { align: 'center', tooltip: true, prop: 'time', label: '结算时间' }
]
export const settlementOrderThead = [
    { align: 'center', tooltip: true, prop: 'businessTypeDesc', label: '业务类型', width: 110 },
    { align: 'center', tooltip: true, prop: 'merchantNo', label: '商户号', width: 110 },
    { align: 'center', tooltip: true, prop: 'operationMode', label: '运营模式', width: 110, slot: true },
    // { align: 'center', tooltip: true, prop: 'collectionMerchantNo', label: '收款方商户号', width: 110 },
    { align: 'center', tooltip: true, prop: 'orderNo', label: '业务订单号', width: 110 },
    { align: 'center', tooltip: true, prop: 'subOrderNo', label: '子订单号', width: 110 },
    { align: 'center', tooltip: true, prop: 'thirdOrderNo', label: '三方支付订单号', width: 130 },
    { align: 'center', tooltip: true, prop: 'settlementAmount', label: '结算金额', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementAccountDesc', label: '结算账户', width: 110 },
    { align: 'center', tooltip: true, prop: 'payTypeDesc', label: '支付方式', width: 110 },
    { align: 'center', tooltip: true, prop: 'settlementTypeDesc', label: '结算类型', width: 110 },
    { align: 'center', tooltip: true, prop: 'payTime', label: '支付成功时间', width: 120 },
    { align: 'center', tooltip: true, prop: 'deviceNo', label: '设备编号', width: 110 },
    { align: 'center', tooltip: true, prop: 'orderAmount', label: '订单金额', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'platSubsidy', label: '补贴金额', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'realPay', label: '用户实付', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'merchantDisctAmount', label: '柜主平台补贴收入', width: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'subLedgerDisctAmount', label: '分账人平台补贴', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'refundNodeDesc', label: '退款节点', width: 120 },
    { align: 'center', tooltip: true, prop: 'refundAmount', label: '退货款', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'disctRefundAmount', label: '退补贴', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'wechatServiceFee', label: '微信手续费', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'platServiceFee', label: '平台服务费', width: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'algorithmFeeAmount', label: '算法使用费', width: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'subLedgerAmount', label: '分账方金额(元)', width: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementTime', label: '结算时间', width: 110 }
]
export const cabinetOwnerThead = [
    { align: 'center', tooltip: true, prop: 'businessType', label: '业务线', width: 90, slot: true },
    // { align: 'center', tooltip: true, prop: 'businessScenario', label: '业务场景', width: 90 },
    { align: 'center', tooltip: true, prop: 'entityUserId', label: '商户号', width: 90 },
    { align: 'center', tooltip: true, prop: 'deviceNo', label: '设备号', width: 90 },
    { align: 'center', tooltip: true, prop: 'deviceName', label: '设备名称', width: 90 },
    { align: 'center', tooltip: true, prop: 'name', label: '分账方/企业名称', width: 130 },
    { align: 'center', tooltip: true, prop: 'type', label: '分账方类型', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'accountNo', label: '分账方账号', width: 110 },
    { align: 'center', tooltip: true, prop: 'mobile', label: '分账人手机号', width: 120 },
    { align: 'center', tooltip: true, prop: 'period', label: '分账周期', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'channel', label: '渠道', width: 70, slot: true },
    { align: 'center', tooltip: true, prop: 'rate', label: '分账比例', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'startTime', label: '分账生效时间', width: 130 },
    { align: 'center', tooltip: true, prop: 'endTime', label: '分账失效时间', width: 130 },
    { align: 'center', tooltip: true, prop: 'status', label: '状态', width: 70, slot: true },
    { align: 'center', tooltip: true, prop: 'deviceStatus', label: '合作状态', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'createTime', label: '创建时间', width: 130 }
]
export const ledgerOwnerThead = [
    { align: 'center', tooltip: true, prop: 'businessTypeDesc', label: '业务线', width: 90, fixed: true },
    // { align: 'center', tooltip: true, prop: 'businessScenario', label: '业务场景', width: 90 },
    { align: 'center', tooltip: true, prop: 'entityUserId', label: '柜主ID', width: 90 },
    { align: 'center', tooltip: true, prop: 'deviceNo', label: '设备编号', width: 90 },
    { align: 'center', tooltip: true, prop: 'deviceName', label: '设备名称', width: 90 },
    { align: 'center', tooltip: true, prop: 'type', label: '分账方类型', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'subLedgerId', label: '分账方ID', width: 110 },
    { align: 'center', tooltip: true, prop: 'name', label: '分账方/企业名称', width: 130 },
    { align: 'center', tooltip: true, prop: 'accountId', label: '分账方账号', width: 130 },
    { align: 'center', tooltip: true, prop: 'mobile', label: '分账方手机号', width: 120 },
    // { align: 'center', tooltip: true, prop: 'period', label: '分账周期', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'channelDesc', label: '渠道', width: 70 },
    { align: 'center', tooltip: true, prop: 'rate', label: '分账比例', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'subsidyFlag', label: '平台优惠券分账', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'deviceStatusDesc', label: '设备绑定状态', width: 130 },
    { align: 'center', tooltip: true, prop: 'createTime', label: '创建时间', width: 130 },
    { align: 'center', tooltip: true, prop: 'unbindTime', label: '解绑时间', width: 130 },
    { align: 'center', tooltip: true, prop: 'updateTime', label: '修改时间', width: 130 }
]
export const ledgerDetailThead = [
    { align: 'center', tooltip: true, prop: 'orderNo', label: '订单号', width: 120, fixed: true },
    // { align: 'center', tooltip: true, prop: 'businessScenario', label: '业务场景', width: 90 },
    { align: 'center', tooltip: true, prop: 'subOrderNo', label: '子订单号', width: 120 },
    { align: 'center', tooltip: true, prop: 'merchantNo', label: '柜主ID', width: 90 },
    { align: 'center', tooltip: true, prop: 'deviceNo', label: '设备编号', width: 90 },
    { align: 'center', tooltip: true, prop: 'orderAmount', label: '订单金额', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementRate', label: '分账比例', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'collectionMerchantName', label: '分账方名称', width: 130 },
    { align: 'center', tooltip: true, prop: 'collectionMerchantNo', label: '收款方平台商户号', width: 150 },
    { align: 'center', tooltip: true, prop: 'accountIn', label: '分账方openid/商户号', width: 170 },
    // { align: 'center', tooltip: true, prop: 'period', label: '分账周期', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementStatus', label: '分账状态', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementAmount', label: '分账金额', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'disctAmount', label: '平台补贴金额', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementTime', label: '结算时间', width: 130 }
]
export const merchantThead = [
    { align: 'center', tooltip: true, prop: 'entityUserId', label: '业务线商户号', width: 120, fixed: true },
    { align: 'center', tooltip: true, prop: 'mainOrderNo', label: '业务订单号', width: 120 },
    { align: 'center', tooltip: true, prop: 'subOuterOrderNo', label: '子订单号', width: 90 },
    { align: 'center', tooltip: true, prop: 'settlementUnitNo', label: '券码ID', width: 90 },
    { align: 'center', tooltip: true, prop: 'incomeAmount', label: '结算金额', width: 110, slot: true },
    { align: 'center', tooltip: true, prop: 'payTypeDesc', label: '支付方式', width: 110 },
    { align: 'center', tooltip: true, prop: 'settlementTypeDesc', label: '结算类型', width: 130 },
    { align: 'center', tooltip: true, prop: 'settlementAccountDesc', label: '结算账户', width: 150 },
    { align: 'center', tooltip: true, prop: 'skuName', label: '商品名称', width: 170 },
    { align: 'center', tooltip: true, prop: 'payTime', label: '支付成功时间', width: 130 },
    { align: 'center', tooltip: true, prop: 'orderAmount', label: '订单金额', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'disctAmount', label: '补贴金额', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'realPayAmount', label: '用户实付', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'merchantDisctAmount', label: '平台补贴收入', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'refundNodeDesc', label: '退款节点', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'goodsRefundAmount', label: '退货款', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'channelRefundfeeAmount', label: '退补贴', width: 90, slot: true },
    { align: 'center', tooltip: true, prop: 'channelScAmount', label: '微信手续费', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'platformScAmount', label: '平台服务费', width: 130, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementTime', label: '结算时间', width: 130 }
]

export const pointsThead = [
    { align: 'center', tooltip: true, prop: 'billNo', label: '账单ID', minWidth: 120 },
    { align: 'center', tooltip: true, prop: 'billMonth', label: '账单日期', minWidth: 120 },
    { align: 'center', tooltip: true, prop: 'orderNum', label: '订单数', minWidth: 90 },
    { align: 'center', tooltip: true, prop: 'algorithmFeeAmount', label: '算法使用费', minWidth: 90 },
    { align: 'center', tooltip: true, prop: 'platformScAmount', label: '平台服务费', minWidth: 110 },
    { align: 'center', tooltip: true, prop: 'payableAmount', label: '应缴金额', minWidth: 110 },
    { align: 'center', tooltip: true, prop: 'payStatusDesc', label: '支付状态', minWidth: 130 },
    { align: 'center', tooltip: true, prop: 'operbtn', label: '操作', minWidth: 150, slot: true }

]
