const formData = {
    brandCode: '',
    spuId: '',
    productFormat: '',
    netWeight: '',
    juiceRatio: '',
    pulpRatio: '',
    drinkStyle: '',
    bestDrinkTime: '',
    attention: '',
    highFiber: '',
    isOrganic: '',
    fatRatio: '',
    calRatio: '',
    proteinRatio: '',
    allergenInfo: '',
    milkAddition: '',
    milkType: '',
    caffRatio: '',
    soybeanAddition: '',
    productTaste: '',
    bacteriaRatio: '',
    sterilizeCraft: '',
    drinkSug: '',
    coffBeanSource: '',
    oatAddition: '',
    dhaRatio: '',
    extractionStyle: '',
    bakingDepth: '',
    bakingAroma: '',
    bakingBitter: '',
    flushedNum: ''
}
const extendImportant = [
    { label: '品牌编号', name: 'brandCode', type: 'input' },
    { label: '标品编码', name: 'spuId', type: 'input', readonly: 'readonly' },
    { label: '产品标准号', name: 'productFormat', type: 'input' },
    { label: '商品净重', name: 'netWeight', type: 'input' },
    { label: '果汁含量', name: 'juiceRatio', type: 'input' },
    { label: '果肉含量', name: 'pulpRatio', type: 'input' },
    { label: '饮用方法', name: 'drinkStyle', type: 'input' },
    { label: '最佳饮用时间', name: 'bestDrinkTime', type: 'input' },
    { label: '注意事项', name: 'attention', type: 'input' },
    { label: '高膳食纤维', name: 'highFiber', type: 'input' },
    { label: '是否有机', name: 'isOrganic', type: 'input' },
    { label: '脂肪含量', name: 'fatRatio', type: 'input' },
    { label: '钙含量', name: 'calRatio', type: 'input' },
    { label: '蛋白质含量', name: 'proteinRatio', type: 'input' },
    { label: '生牛乳添加量', name: 'milkAddition', type: 'input' },
    { label: '乳饮性质', name: 'milkType', type: 'input' },
    { label: '咖啡因含量', name: 'caffRatio', type: 'input' },
    { label: '大豆添加量', name: 'soybeanAddition', type: 'input' },
    { label: '口味', name: 'productTaste', type: 'input' },
    { label: '乳酸菌含量', name: 'bacteriaRatio', type: 'input' },
    { label: '杀菌工艺', name: 'sterilizeCraft', type: 'input' },
    { label: '饮用建议', name: 'drinkSug', type: 'input' },
    { label: '咖啡豆源', name: 'coffBeanSource', type: 'input' },
    { label: '燕麦添加量', name: 'oatAddition', type: 'input' },
    { label: 'DHA含量', name: 'dhaRatio', type: 'input' },
    { label: '萃取方式', name: 'extractionStyle', type: 'input' },
    { label: '烘焙深度', name: 'bakingDepth', type: 'input' },
    { label: '烘焙香气', name: 'bakingAroma', type: 'input' },
    { label: '烘焙苦度', name: 'bakingBitter', type: 'input' },
    { label: '可冲杯数', name: 'flushedNum', type: 'input' }

]
export default {
    tempFormData: formData,
    extendImportant: extendImportant
}
