const formData = {
    brandCode: '',
    spuId: '',
    productFormat: '',
    netWeight: '',
    productTaste: '',
    foodCraft: '',
    processStyle: '',
    productRank: '',
    processCraft: '',
    isTransfat: '',
    milkFatRatio: '',
    cheeseForm: '',
    fatRatio: '',
    milkClass: '',
    calciumRatio: '',
    prebioticsRatio: '',
    butterSaltRatio: '',
    isFerment: '',
    noSucrose: '',
    noVegfat: '',
    milkType: '',
    zeroAdditives: '',
    peopleEatNum: '',
    productTasteBase: '',
    sweetness: '',
    chopQuality: '',
    transFat: '',
    milkOrigPlace: '',
    cheeseCate: '',
    softenStyle: '',
    flourProteinRatio: '',
    sterilizeStyle: '',
    butterFermentStyle: ''
}
const extendImportant = [
    { label: '品牌编号', name: 'brandCode', type: 'input' },
    { label: '标品编码', name: 'spuId', type: 'input', readonly: 'readonly' },
    { label: '产品标准号', name: 'productFormat', type: 'input' },
    { label: '商品净重', name: 'netWeight', type: 'input' },
    { label: '口味', name: 'productTaste', type: 'input' },
    { label: '食品工艺', name: 'foodCraft', type: 'input' },
    { label: '加工方式', name: 'processStyle', type: 'input' },
    { label: '等级', name: 'productRank', type: 'input' },
    { label: '加工工艺', name: 'processCraft', type: 'input' },
    { label: '是否含反式脂肪酸', name: 'isTransfat', type: 'input' },
    { label: '乳脂含量', name: 'milkFatRatio', type: 'input' },
    { label: '奶酪形态', name: 'cheeseForm', type: 'input' },
    { label: '脂肪含量', name: 'fatRatio', type: 'input' },
    { label: '奶类', name: 'milkClass', type: 'input' },
    { label: '钙含量', name: 'calciumRatio', type: 'input' },
    { label: '益生元', name: 'prebioticsRatio', type: 'input' },
    { label: '黄油含盐量', name: 'butterSaltRatio', type: 'input' },
    { label: '是否发酵', name: 'isFerment', type: 'input' },
    { label: '不加蔗糖', name: 'noSucrose', type: 'input' },
    { label: '无植脂末', name: 'noVegfat', type: 'input' },
    { label: '类型', name: 'milkType', type: 'input' },
    { label: '0添加剂', name: 'zeroAdditives', type: 'input' },
    { label: '适合人数', name: 'peopleEatNum', type: 'input' },
    { label: '口味基底', name: 'productTasteBase', type: 'input' },
    { label: '甜度', name: 'sweetness', type: 'input' },
    { label: '餐具数量', name: 'chopQuality', type: 'input' },
    { label: '反式脂肪酸', name: 'transFat', type: 'input' },
    { label: '牛乳产地', name: 'milkOrigPlace', type: 'input' },
    { label: '奶酪类别', name: 'cheeseCate', type: 'input' },
    { label: '软化方法', name: 'softenStyle', type: 'input' },
    { label: '面粉蛋白质含量', name: 'flourProteinRatio', type: 'input' },
    { label: '杀菌方式', name: 'sterilizeStyle', type: 'input' },
    { label: '黄油发酵方法', name: 'butterFermentStyle', type: 'input' }
]
export default {
    tempFormData: formData,
    extendImportant: extendImportant
}
