const formData = {
    brandCode: '',
    spuId: '',
    productFormat: '',
    netWeight: '',
    prodMaterial: '',
    productTasteType: '',
    nursingType: '',
    specialType: '',
    availPart: '',
    spf: '',
    paValue: '',
    mainIngredient: '',
    medicalRegistNo: '',
    medicalClass: '',
    isMedical: '',
    model: '',
    gearMode: '',
    power: '',
    chargeMode: '',
    endurance: '',
    opMode: '',
    waterCap: '',
    frequency: '',
    fragrance: '',
    availPerson: '',
    effect: '',
    function: '',
    eyelashClass: '',
    isWaterproof: '',
    isLimited: '',
    isMenCare: '',
    reMakeupCate: '',
    isSpecial: '',
    honeyPowderCate: '',
    availHair: '',
    availScalp: ''
}
const extendImportant = [
    { label: '品牌编号', name: 'brandCode', type: 'input' },
    { label: '标品编码', name: 'spuId', type: 'input', readonly: 'readonly' },
    { label: '产品标准号', name: 'productFormat', type: 'input' },
    { label: '商品净重', name: 'netWeight', type: 'input' },
    { label: '商品材质', name: 'prodMaterial', type: 'input' },
    { label: '香型', name: 'productTasteType', type: 'input' },
    { label: '类型', name: 'nursingType', type: 'input' },
    { label: '特殊化妆品类型', name: 'specialType', type: 'input' },
    { label: '适用部位', name: 'availPart', type: 'input' },
    { label: '防晒指数', name: 'spf', type: 'input' },
    { label: 'PA值', name: 'paValue', type: 'input' },
    { label: '主要成分', name: 'mainIngredient', type: 'input' },
    { label: '医疗器械注册证编号', name: 'medicalRegistNo', type: 'input' },
    { label: '医疗器械类别', name: 'medicalClass', type: 'input' },
    { label: '是否医疗器械', name: 'isMedical', type: 'input' },
    { label: '型号', name: 'model', type: 'input' },
    { label: '档位模式', name: 'gearMode', type: 'input' },
    { label: '功率', name: 'power', type: 'input' },
    { label: '充电方式', name: 'chargeMode', type: 'input' },
    { label: '续航时间', name: 'endurance', type: 'input' },
    { label: '工作方式', name: 'opMode', type: 'input' },
    { label: '水箱容量', name: 'waterCap', type: 'input' },
    { label: '震频', name: 'frequency', type: 'input' },
    { label: '香调', name: 'fragrance', type: 'input' },
    { label: '适用对象', name: 'availPerson', type: 'input' },
    { label: '功效', name: 'effect', type: 'input' },
    { label: '功能', name: 'function', type: 'input' },
    { label: '睫毛产品分类', name: 'eyelashClass', type: 'input' },
    { label: '是否防水', name: 'isWaterproof', type: 'input' },
    { label: '是否量贩装', name: 'isLimited', type: 'input' },
    { label: '男士护理单品', name: 'isMenCare', type: 'input' },
    { label: '卸妆分类', name: 'reMakeupCate', type: 'input' },
    { label: '是否为特殊用途化妆品', name: 'isSpecial', type: 'input' },
    { label: '蜜粉散粉分类', name: 'honeyPowderCate', type: 'input' },
    { label: '适用发质', name: 'availHair', type: 'input' },
    { label: '适合头皮', name: 'availScalp', type: 'input' }
]
export default {
    tempFormData: formData,
    extendImportant: extendImportant
}
