export const tHead = [
    { align: 'center', tooltip: true, type: 'selection', minWidth: 60 },
    { align: 'center', tooltip: true, prop: 'userId', label: '主用户id', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'subUserId', label: '子用户id', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'nickName', label: '昵称', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'phoneMobile', label: '手机号', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'wechatOpenId', label: '微信openid', minWidth: 120 },
    { align: 'center', tooltip: true, prop: 'alipayOpenId', label: '支付宝openid', minWidth: 130 },
    { align: 'center', tooltip: true, prop: 'batch', label: '渠道来源', minWidth: 130 },
    { align: 'center', tooltip: true, prop: 'busiCode', label: '所属业务线', minWidth: 150, slot: true },
    { align: 'center', tooltip: true, prop: 'regType', label: '注册方式', minWidth: 100, slot: true },
    { align: 'center', tooltip: true, prop: 'regTime', label: '注册时间', minWidth: 200 },
    { align: 'center', tooltip: true, prop: 'expiredTime', label: '登录信息到期时间', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'loginStatus', label: '登录状态', minWidth: 160, slot: true },
    { align: 'center', tooltip: true, prop: 'userStatus', label: '用户状态', minWidth: 160, slot: true },
    { align: 'center', tooltip: true, prop: 'statusChangeTime', label: '状态变更时间', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'isAddress', label: '收货地址', minWidth: 100, slot: true },
    { align: 'center', tooltip: true, prop: 'operation', label: '操作', minWidth: 100, slot: true }
]
export const distributionThead = [
    { align: 'center', tooltip: true, prop: 'id', label: '主用户id', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'busiUserId', label: '子用户id', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'nickName', label: '昵称', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'phoneMobile', label: '手机号', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'busiCode', label: '所属业务线', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'regType', label: '注册方式', minWidth: 100, slot: true },
    { align: 'center', tooltip: true, prop: 'regTime', label: '注册时间', minWidth: 200 },
    { align: 'center', tooltip: true, prop: 'role', label: '分销角色', minWidth: 150, slot: true },
    { align: 'center', tooltip: true, prop: 'roleStatus', label: '分销角色状态', minWidth: 160, slot: true },
    { align: 'center', tooltip: true, prop: 'gmtModify', label: '状态变更时间', minWidth: 160 },
    { align: 'center', tooltip: true, prop: 'roleRelationStatus', label: '关联关系', minWidth: 150, slot: true },
    { align: 'center', tooltip: true, prop: 'inviterRole', label: '上级角色', minWidth: 160, slot: true },
    { align: 'center', tooltip: true, prop: 'inviterRoleStatus', label: '上级分销角色状态', minWidth: 160, slot: true },
    { align: 'center', tooltip: true, prop: 'inviterPhoneMobile', label: '上级手机号', minWidth: 160 }
]
