import {createRouter,createWebHistory} from 'vue-router'
//createRouter方法，用于创建路由器实例，可以管理多个路由
export default createRouter({
    //路由的模式的设置
    history:createWebHistory(),
    routes:[
        {
            path:"/home",
            component:()=>import("@/pages/home/index.vue"),
            meta:{
                title:'首页'
            }
        },
        {
            path:"/hospital",
            component:()=>import("@/pages/hospital/index.vue"),
            children:[
                {
                    path:"/hospital/register",
                    component:()=>import("@/pages/hospital/register/index.vue"),
                    meta:{
                        title:'预约挂号'
                    }
                },
                {
                    path:"/hospital/register_step1",
                    component:()=>import("@/pages/hospital/register/register_step1.vue"),
                    meta:{
                        title:'预约第一步'
                    }
                },
                {
                    path:"/hospital/register_step2",
                    component:()=>import("@/pages/hospital/register/register_step2.vue"),
                    meta:{
                        title:'预约第二步'
                    }
                },
                {
                    path:"/hospital/detail",
                    component:()=>import("@/pages/hospital/detail/index.vue"),
                    meta:{
                        title:'医院详情'
                    }
                },
                {
                    path:"/hospital/notice",
                    component:()=>import("@/pages/hospital/notice/index.vue"),
                    meta:{
                        title:'预约通知'
                    }
                },
                {
                    path:"/hospital/close",
                    component:()=>import("@/pages/hospital/close/index.vue"),
                    meta:{
                        title:'停诊信息'
                    }
                },
                {
                    path:"/hospital/search",
                    component:()=>import("@/pages/hospital/search/index.vue"),
                    meta:{
                        title:'查询'
                    }
                }
            ]
        },
        {
            path:"/wxlogin",
            component:()=>import("@/pages/wxlogin/index.vue"),
            meta:{
                title:'微信登录'
            }
        },
        {
            path:"/user",
            component:()=>import('@/pages/user/index.vue'),
            children:[
                {
                    path:'/user/certification',
                    component:()=>import('@/pages/user/certification/index.vue'),
                    meta:{
                        title:'实名认证'
                    }
                },
                {
                    path:'/user/order',
                    component:()=>import('@/pages/user/order/index.vue'),
                    meta:{
                        title:'挂号订单'
                    }
                },
                {
                    path:'/user/patient',
                    component:()=>import('@/pages/user/patient/index.vue'),
                    meta:{
                        title:'就诊人管理'
                    }
                },
                {
                    path:'/user/profile',
                    component:()=>import('@/pages/user/profile/index.vue'),
                    meta:{
                        title:'账号信息'
                    }
                },
                {
                    path:'/user/feedback',
                    component:()=>import('@/pages/user/feedback/index.vue'),
                    meta:{
                        title:'意见反馈'
                    }
                }
            ]
        },
        {
            path:"/",
            redirect:"/home"
        }
    ],
    //滚动行为：控制滚动条的位置
    scrollBehavior(){
        return{
            top:0,
            left:0
        }
    }
})