export const tHead = [
    { align: 'center', tooltip: true, prop: 'businessTypeDesc', label: '业务类型', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'merchantNo', label: '商户号', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'merchantModelDesc', label: '运营模式', minWidth: 150 },
    { align: 'center', tooltip: true, prop: 'orderNo', label: '业务订单号', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'subOrderNo', label: '子订单号', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'thirdOrderNo', label: '三方支付订单号', minWidth: 200 },
    { align: 'center', tooltip: true, prop: 'settlementAmount', label: '结算金额(元)', minWidth: 120, slot: true },
    { align: 'center', prop: 'settlementAccountDesc', label: '结算账户', minWidth: 120 },
    { align: 'center', prop: 'payTypeDesc', label: '支付方式', minWidth: 120 },
    { align: 'center', tooltip: true, prop: 'settlementTypeDesc', label: '结算类型', minWidth: 200 },
    { align: 'center', tooltip: true, prop: 'payTime', label: '支付成功时间', minWidth: 180 },
    { align: 'center', tooltip: true, prop: 'orderAmount', label: '订单金额(元)', minWidth: 200, slot: true },
    { align: 'center', tooltip: true, prop: 'platSubsidy', label: '补贴金额(元)', minWidth: 200, slot: true },
    { align: 'center', tooltip: true, prop: 'realPay', label: '用户实付(元)', minWidth: 200, slot: true },
    { align: 'center', tooltip: true, prop: 'merchantDisctAmount', label: '平台补贴收入(元)', minWidth: 200, slot: true },
    { align: 'center', tooltip: true, prop: 'refundNodeDesc', label: '退款节点', minWidth: 100 },
    { align: 'center', tooltip: true, prop: 'refundAmount', label: '退款货款(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'disctRefundAmount', label: '退款补贴(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'wechatServiceFee', label: '微信手续费(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'platServiceFee', label: '平台服务费(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'algorithmFeeAmount', label: '算法使用费(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'subLedgerAmount', label: '分账方金额(元)', minWidth: 120, slot: true },
    { align: 'center', tooltip: true, prop: 'settlementTime', label: '结算时间', minWidth: 180 }
]
